language: ruby
script: "script/test_all"
bundler_args: "--standalone --binstubs --without documentation"
before_install:
  - gem update --system --conservative || (gem i "rubygems-update:~>2.7" --no-document && update_rubygems)
  - gem update bundler --conservative

# In order to install old Rubies, we need to use old Ubuntu distibution.
dist: trusty

rvm:
  - 2.6.6
  - truffleruby-head
  - truffleruby
env:
  - BRANCH=master
  - BRANCH=2-99-maintenance
